from app.config import AppConfig
from app.runtime import get_tools
from app.tools import get_builtin_tools


def test_builtin_tool_registry_contains_expected_tools():
    tools = get_builtin_tools()

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "present_files",
        "get_time",
    ]


def test_runtime_returns_builtin_tools():
    tools = get_tools(AppConfig(model_name="openai:gpt-4o-mini"))

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "present_files",
        "get_time",
    ]


def test_present_files_tool_formats_paths_and_summary():
    present_files = next(tool for tool in get_builtin_tools() if tool.name == "present_files")

    result = present_files.invoke(
        {
            "paths": ["outputs/report.md", "outputs/summary.txt"],
            "summary": "Generated by the lite runtime.",
        }
    )

    assert "Files:" in result
    assert "- outputs/report.md" in result
    assert "Summary: Generated by the lite runtime." in result
