from pathlib import Path

from app.config import AppConfig
from app.runtime import get_tools
from app.tools import get_builtin_tools
from app.tools.builtin.fetch import _extract_page_content
from app.tools.builtin.present_files import present_file_listing, resolve_artifact_paths
from app.tools.builtin.search import _parse_search_results
from app.tools.builtin.write_report import write_report_file


def test_builtin_tool_registry_contains_expected_tools():
    tools = get_builtin_tools()

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "web_search",
        "web_fetch",
        "write_report",
        "present_files",
    ]


def test_runtime_returns_builtin_tools():
    tools = get_tools(AppConfig(model_name="openai:gpt-4o-mini"))

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "web_search",
        "web_fetch",
        "write_report",
        "present_files",
    ]


def test_runtime_injected_tool_schemas_are_json_serializable():
    tools = {tool.name: tool for tool in get_builtin_tools()}

    assert tools["write_report"].args == {
        "content": {"title": "Content", "type": "string"},
        "filename": {"default": "report.md", "title": "Filename", "type": "string"},
    }
    assert tools["present_files"].args == {
        "paths": {"items": {"type": "string"}, "title": "Paths", "type": "array"},
        "summary": {
            "anyOf": [{"type": "string"}, {"type": "null"}],
            "default": None,
            "title": "Summary",
        },
    }


def test_present_files_tool_formats_paths_and_summary():
    result = present_file_listing(
        ["outputs/report.md", "outputs/summary.txt"],
        summary="Generated by the lite runtime.",
    )

    assert "Files:" in result
    assert "- .deerflow/threads/default/outputs/report.md" in result
    assert "Summary: Generated by the lite runtime." in result


def test_resolve_artifact_paths_uses_thread_outputs_directory(tmp_path: Path):
    artifacts = resolve_artifact_paths(
        ["report.md", "outputs/summary.txt", "report.md"],
        thread_id="thread-1",
        base_dir=tmp_path,
    )

    assert artifacts == [
        "threads/thread-1/outputs/report.md",
        "threads/thread-1/outputs/summary.txt",
    ]


def test_parse_search_results_extracts_titles_urls_and_snippets():
    html = """
    <div class="result results_links results_links_deep web-result ">
      <div class="links_main links_deep result__body">
        <h2 class="result__title">
          <a class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fexample.com%2Farticle">Example Title</a>
        </h2>
        <a class="result__snippet">Example snippet text.</a>
      </div>
    </div>
    """

    results = _parse_search_results(html, max_results=5)

    assert results == [
        {
            "title": "Example Title",
            "url": "https://example.com/article",
            "snippet": "Example snippet text.",
        }
    ]


def test_extract_page_content_strips_script_and_keeps_title():
    html = """
    <html>
      <head>
        <title>Example Page</title>
        <script>ignored()</script>
      </head>
      <body>
        <h1>Hello</h1>
        <p>World</p>
      </body>
    </html>
    """

    title, text = _extract_page_content(html)

    assert title == "Example Page"
    assert "Hello" in text
    assert "World" in text
    assert "ignored" not in text


def test_write_report_file_writes_into_thread_outputs(tmp_path: Path):
    output_path = write_report_file(
        "# Report\n\nContent",
        thread_id="thread-1",
        base_dir=tmp_path,
    )

    assert output_path == tmp_path / "threads" / "thread-1" / "outputs" / "report.md"
    assert output_path.read_text(encoding="utf-8") == "# Report\n\nContent"
