from pathlib import Path

from north.config import AppConfig
from north.runtime import get_tools
from north.tools import get_builtin_tools
from north.tools.builtin.fetch import _extract_page_content
from north.tools.builtin.list_files import format_file_listing, list_thread_file_uris
from north.tools.builtin.present_files import present_file_listing, resolve_artifact_paths
from north.tools.builtin.read_file import read_text_file
from north.tools.builtin.search import _parse_search_results
from north.tools.builtin.write_report import write_report_file


def test_builtin_tool_registry_contains_expected_tools():
    tools = get_builtin_tools()

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "list_files",
        "read_file",
        "web_search",
        "web_fetch",
        "write_report",
        "present_files",
    ]


def test_runtime_returns_builtin_tools():
    tools = get_tools(AppConfig(model_name="openai:gpt-4o-mini"))

    assert [tool.name for tool in tools] == [
        "ask_clarification",
        "list_files",
        "read_file",
        "web_search",
        "web_fetch",
        "write_report",
        "present_files",
    ]


def test_runtime_injected_tool_schemas_are_json_serializable():
    tools = {tool.name: tool for tool in get_builtin_tools()}

    assert set(tools["ask_clarification"].args) == {
        "question",
        "response_kind",
        "options",
    }

    assert tools["read_file"].args == {
        "path": {"title": "Path", "type": "string"},
    }
    assert tools["list_files"].args == {
        "domain": {"default": "all", "title": "Domain", "type": "string"},
    }
    assert tools["write_report"].args == {
        "content": {"title": "Content", "type": "string"},
        "filename": {"default": "report.md", "title": "Filename", "type": "string"},
    }
    assert tools["present_files"].args == {
        "paths": {"items": {"type": "string"}, "title": "Paths", "type": "array"},
        "summary": {
            "anyOf": [{"type": "string"}, {"type": "null"}],
            "default": None,
            "title": "Summary",
        },
    }


def test_present_files_tool_formats_paths_and_summary(tmp_path: Path):
    result = present_file_listing(
        ["outputs/report.md", "outputs/summary.txt"],
        summary="Generated by the lite runtime.",
        base_dir=tmp_path,
    )

    assert "Files:" in result
    assert "- threads/default/outputs/report.md" in result
    assert "Summary: Generated by the lite runtime." in result


def test_resolve_artifact_paths_uses_thread_outputs_directory(tmp_path: Path):
    artifacts = resolve_artifact_paths(
        ["report.md", "outputs/summary.txt", "report.md"],
        thread_id="thread-1",
        base_dir=tmp_path,
    )

    assert artifacts == [
        "threads/thread-1/outputs/report.md",
        "threads/thread-1/outputs/summary.txt",
    ]


def test_list_thread_file_uris_returns_thread_resource_uris(tmp_path: Path):
    thread_root = tmp_path / "threads" / "thread-1"
    (thread_root / "uploads").mkdir(parents=True)
    (thread_root / "workspace" / "notes").mkdir(parents=True)
    (thread_root / "outputs").mkdir(parents=True)
    (thread_root / "memory").mkdir(parents=True)
    (thread_root / "uploads" / "brief.md").write_text("brief", encoding="utf-8")
    (thread_root / "workspace" / "notes" / "analysis.md").write_text("analysis", encoding="utf-8")
    (thread_root / "outputs" / "report.md").write_text("report", encoding="utf-8")

    uris = list_thread_file_uris(thread_id="thread-1", base_dir=tmp_path)

    assert uris == [
        "upload://brief.md",
        "workspace://notes/analysis.md",
        "output://report.md",
    ]


def test_list_thread_file_uris_can_filter_domain(tmp_path: Path):
    thread_root = tmp_path / "threads" / "thread-1"
    (thread_root / "uploads").mkdir(parents=True)
    (thread_root / "outputs").mkdir(parents=True)
    (thread_root / "uploads" / "brief.md").write_text("brief", encoding="utf-8")
    (thread_root / "outputs" / "report.md").write_text("report", encoding="utf-8")

    uris = list_thread_file_uris(thread_id="thread-1", domain="output", base_dir=tmp_path)

    assert uris == ["output://report.md"]


def test_format_file_listing_handles_empty_and_present_files():
    assert format_file_listing([]) == "No files found."
    assert format_file_listing(["upload://brief.md"]) == "Files:\n- upload://brief.md"


def test_parse_search_results_extracts_titles_urls_and_snippets():
    html = """
    <div class="result results_links results_links_deep web-result ">
      <div class="links_main links_deep result__body">
        <h2 class="result__title">
          <a class="result__a" href="//duckduckgo.com/l/?uddg=https%3A%2F%2Fexample.com%2Farticle">Example Title</a>
        </h2>
        <a class="result__snippet">Example snippet text.</a>
      </div>
    </div>
    """

    results = _parse_search_results(html, max_results=5)

    assert results == [
        {
            "title": "Example Title",
            "url": "https://example.com/article",
            "snippet": "Example snippet text.",
        }
    ]


def test_extract_page_content_strips_script_and_keeps_title():
    html = """
    <html>
      <head>
        <title>Example Page</title>
        <script>ignored()</script>
      </head>
      <body>
        <h1>Hello</h1>
        <p>World</p>
      </body>
    </html>
    """

    title, text = _extract_page_content(html)

    assert title == "Example Page"
    assert "Hello" in text
    assert "World" in text
    assert "ignored" not in text


def test_write_report_file_writes_into_thread_outputs(tmp_path: Path):
    output_path = write_report_file(
        "# Report\n\nContent",
        thread_id="thread-1",
        base_dir=tmp_path,
    )

    assert output_path == tmp_path / "threads" / "thread-1" / "outputs" / "report.md"
    assert output_path.read_text(encoding="utf-8") == "# Report\n\nContent"


def test_read_text_file_allows_only_configured_roots(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    readable = skills_dir / "research" / "SKILL.md"
    readable.parent.mkdir(parents=True)
    readable.write_text("content", encoding="utf-8")

    assert read_text_file(
        "skill://research/SKILL.md",
        thread_id="thread-1",
        skills_dir=skills_dir,
        thread_base_dir=tmp_path / ".deerflow",
    ) == "content"


def test_read_text_file_rejects_paths_outside_allowed_roots(tmp_path: Path):
    skills_dir = tmp_path / "skills"
    skills_dir.mkdir()

    try:
        read_text_file(
            "skill://../outside.md",
            thread_id="thread-1",
            skills_dir=skills_dir,
            thread_base_dir=tmp_path / ".deerflow",
        )
        assert False, "Expected read_text_file to reject escaped resource URIs"
    except ValueError as exc:
        assert "must not escape" in str(exc)
